name: Nexo Full Alert System

on:
  schedule:
    - cron: '0 */6 * * *'  # 매 6시간마다 실행
  workflow_dispatch:

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 matplotlib

      - name: Load Previous Caches
        run: |
          cp news_cache.txt previous_news.txt || touch news_cache.txt
          cp tweet_cache.txt previous_tweets.txt || touch tweet_cache.txt
          cp price_cache.txt previous_price.txt || echo "0" > price_cache.txt

      - name: Run Nexo Alert Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python alert_nexo.py

      - name: Save Caches
        run: |
          cp news_cache.txt previous_news.txt
          cp tweet_cache.txt previous_tweets.txt
          tail -n 1 price_cache.txt > previous_price.txt
