# .github/workflows/nexo_news_alert.yml

name: Nexo Full Alert System

on:
  schedule:
    - cron: '0 */6 * * *'  # 매 6시간마다 실행
  workflow_dispatch:

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 matplotlib

      - name: Restore News Cache
        run: |
          if [ -f previous_news.txt ]; then
            cp previous_news.txt news_cache.txt
          else
            touch news_cache.txt
          fi

      - name: Restore Tweet Cache
        run: |
          if [ -f previous_tweets.txt ]; then
            cp previous_tweets.txt tweet_cache.txt
          else
            touch tweet_cache.txt
          fi

      - name: Restore Price Cache
        run: |
          if [ -f previous_price.txt ]; then
            cp previous_price.txt price_cache.txt
          else
            echo "0" > price_cache.txt
          fi

      - name: Run Nexo Alert Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python alert_nexo.py

      - name: Save News Cache
        run: cp news_cache.txt previous_news.txt

      - name: Save Tweet Cache
        run: cp tweet_cache.txt previous_tweets.txt

      - name: Save Price Cache
        run: tail -n 28 price_cache.txt > previous_price.txt
